# Generated by Django 5.1.1 on 2024-10-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_email_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_id',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='veg_id',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
    ]
