# Generated by Django 5.1.1 on 2024-10-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
