# Generated by Django 5.1.1 on 2024-10-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_id',
        ),
    ]
